# For more information on this configuration, see the complete reference guide at
# https://github.com/grafana/mimir/blob/main/docs/sources/mimir/configure/configuration-parameters/index.md
# https://grafana.com/docs/mimir/latest/references/configuration-parameters/

# Disable multi-tenancy and restrict to single tenant
multitenancy_enabled: false

# (advanced) Tenant ID to use when multitenancy is disabled
no_auth_tenant: sembark

# (experimental) Maximum number of groups allowed per tenant by which specified
# distributor and ingester metrics can be further separated
max_separate_metrics_groups_per_user: 10000

# The server block configures the Mimir server
server:
  # Listen on port 9009 for all incoming requests.
  http_listen_port: 9009
  # Log messages at info level.
  log_level: info

common:
  storage:
    # Backend storage to use. Supported backends are: s3, gcs, azure, swift,
    # filesystem.
    # CLI flag: -common.storage.backend
    backend: s3
    s3:
      endpoint: s3.ap-south-1.amazonaws.com
      region: ap-south-1
      access_key_id: ${AWS_ACCESS_KEY_ID} # This is a secret injected via an environment variable
      secret_access_key: ${AWS_SECRET_ACCESS_KEY} # This is a secret injected via an environment variable

# The block storage configuration determines where the metrics TSDB data is stored.
blocks_storage:
  # Directory in which to store configuration for object storage.
  filesystem:
    dir: /var/lib/mimir/blocks
  s3:
    bucket_name: ${AWS_S3_BUCKET}
  storage_prefix: "mimirBlocks"

  # This configures how the querier and store-gateway discover and synchronize
  # blocks stored in the bucket
  bucket_store:
    # Directory to store synchronized TSDB index headers. This directory is not
    # required to be persisted between restarts, but it's highly recommended in
    # order to improve the store-gateway startup time.
    sync_dir: /var/lib/mimir/tsdb-sync
    chunks_cache:
      backend: memcached
      memcached:
        addresses: ${MEMCACHED_ADDRESS}
    metadata_cache:
      backend: memcached
      memcached:
        addresses: ${MEMCACHED_ADDRESS}

  tsdb:
    # Directory to store TSDBs (including WAL) in the ingesters.
    # This directory is required to be persisted between restarts.
    dir: /var/lib/mimir/tsdb

alertmanager_storage:
  filesystem:
    # The directory in which to store alertmanager data
    dir: /var/lib/mimir/alertmanager
  s3:
    bucket_name: ${AWS_S3_BUCKET}
  storage_prefix: "mimirAlertManager"

# The ruler storage block configures ruler storage settings.
ruler_storage:
  filesystem:
    # The directory in which to store rules.
    dir: /var/lib/mimir/ruler
  s3:
    bucket_name: ${AWS_S3_BUCKET}
  storage_prefix: "mimirRuler"

# Ingester receives data from the distributor and processes it into indices and blocks
ingester:
  ring:
    # Run only one instance of the ingesters
    # WARN: It is highly recommended to run more than one ingester in
    # production (default is 3)
    replication_factor: 1

# Configure the compactor responsible for compacting TSDB blocks
compactor:
  # Directory to temporarily store blocks undergoing compaction.
  # Any corrupt/partial block (i.e. without meta.json file) in this directory
  # will automatically be deleted after limits.compactor_partial_block_deletion_delay.
  # As a result, this directory's size is also kept under control automatically.
  data_dir: /var/lib/mimir/compactor
  # (experimental) If enabled, the compactor constructs and uploads sparse index
  # headers to object storage during each compaction cycle. This allows
  # store-gateway instances to use the sparse headers from object storage instead
  # of recreating them locally.
  # CLI flag: -compactor.upload-sparse-index-headers
  upload_sparse_index_headers: true

# Configure store-gateway component to connect to the object storage
store_gateway:
  # Configuration for the hash ring.
  sharding_ring:
    # Run a single instance
    # WARN: In production setups, the replication factor must
    # be set on the querier and ruler as well
    replication_factor: 1

# Global limits configuration.
limits:
  # Automatically delete blocks containing samples older than 2.5 months.
  # This helps with keeping S3 bucket size under control.
  compactor_blocks_retention_period: 10w

  # (experimental) The maximum number of exemplars in memory, across the cluster.
  # 0 to disable exemplars ingestion.
  # This setting enables exemplar processing and storage.
  # CLI flag: -ingester.max-global-exemplars-per-user
  max_global_exemplars_per_user: 100000

  # Per-tenant ingestion rate limit in samples per second.
  # CLI flag: -distributor.ingestion-rate-limit
  ingestion_rate: 30000

  # Enable Native Histograms
  native_histograms_ingestion_enabled: true
  # Samples with more buckets than the limit will be scaled down, meaning that
  # the resolution will be reduced and buckets will be merged until either the
  # number of buckets is under the limit or the minimal resolution is reached
  max_native_histogram_buckets: 160

  # (experimental) Whether to keep identifying OTel resource attributes in the
  # target_info metric on top of converting to job and instance labels
  # CLI flag: -distributor.otel-keep-identifying-resource-attributes
  otel_keep_identifying_resource_attributes: true
  # (experimental) Optionally specify OTel resource attributes to promote to labels
  # CLI flag: -distributor.otel-promote-resource-attributes
  promote_otel_resource_attributes: "service.instance.id, service.name, service.namespace, service.version, cloud.availability_zone, cloud.region, container.name, deployment.environment, deployment.environment.name, k8s.cluster.name, k8s.container.name, k8s.cronjob.name, k8s.daemonset.name, k8s.deployment.name, k8s.job.name, k8s.namespace.name, k8s.pod.name, k8s.replicaset.name, k8s.statefulset.name"
